# Generated by Django 2.2.16 on 2022-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220617_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
