# Generated by Django 2.2.16 on 2022-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cost_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='chat_id',
            field=models.IntegerField(default=1186342765),
            preserve_default=False,
        ),
    ]
