# Generated by Django 2.2.19 on 2022-12-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cost_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='api.Group'),
        ),
    ]
