GET http://dmitrypetukhov90.pythonanywhere.com/api/v1/costs/
Content-type: application/json; charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU1NTgwNTUzLCJqdGkiOiIyZjE2YTZhZjg1OGQ0MDYwYjA1YjYwNWI2MTY1ODk0OCIsInVzZXJfaWQiOjN9.k7MyOPjIzQ43mZ-5r8OwB0v_Ri7nQasfEbaNGUAWdJc
#Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01
#Authorization: Token b7bb38ae368205d2a058554f96d28f8193634013


###
GET http://dmitrypetukhov90.pythonanywhere.com/api/v1/costs/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

###
POST http://dmitrypetukhov90.pythonanywhere.com/api/v1/costs/
Content-type: application/json; charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU1NTgwNTUzLCJqdGkiOiIyZjE2YTZhZjg1OGQ0MDYwYjA1YjYwNWI2MTY1ODk0OCIsInVzZXJfaWQiOjN9.k7MyOPjIzQ43mZ-5r8OwB0v_Ri7nQasfEbaNGUAWdJc

{
    "cost": 185,
    "group": 2

}

###
GET http://127.0.0.1:8000/api/v1/posts/2/comments/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

###
POST http://127.0.0.1:8000/api/v1/posts/2/comments/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "text": "Тестовый коммент6",
    "author": "username8"

}

###
GET http://127.0.0.1:8000/api/v1/posts/2/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "text": "Тестирую PATCH152"
}

###
POST http://127.0.0.1:8000/api/v1/groups/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "title": "Разное",
    "slug": "Diff",
    "description": "Расходы без категорий."
}

###
POST http://127.0.0.1:8000/api/v1/posts/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "text": "Тестирую пост админ2"
}

###
GET http://127.0.0.1:8000/api/v1/posts/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "text": "коммент3",
    "author": "Автор"
}

###
POST http://127.0.0.1:8000/auth/jwt/create/
Content-type: application/json; charset=utf-8
#Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "username": "admin",
    "password": "20756320"
}

###
POST http://dmitrypetukhov90.pythonanywhere.com/auth/users/
Content-type: application/json; charset=utf-8
#Authorization: Token b7bb38ae368205d2a058554f96d28f8193634013

{
    "username": "Dimon",
    "password": "Zima19011990*"
}

###
POST http://dmitrypetukhov90.pythonanywhere.com/auth/jwt/create/
Content-type: application/json; charset=utf-8
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU1NTgwNTUzLCJqdGkiOiIyZjE2YTZhZjg1OGQ0MDYwYjA1YjYwNWI2MTY1ODk0OCIsInVzZXJfaWQiOjN9.k7MyOPjIzQ43mZ-5r8OwB0v_Ri7nQasfEbaNGUAWdJc

{
    "username": "Dimon",
    "password": "Zima19011990*"
}