GET http://dmitrypetukhov90.pythonanywhere.com/api/v1/costs/1186342765
Content-type: application/json; charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU1NjY0NDMyLCJqdGkiOiJlYjY3ZmZmYTdiMGU0YmEzOTMyZDQ2ZjU4MTljOWMyMSIsInVzZXJfaWQiOjN9.ePbYAuYlCK3Q_2z7wG8o-fT1Cs0a40qoAHglrPGMjco
#Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01
#Authorization: Token b7bb38ae368205d2a058554f96d28f8193634013


###
GET http://dmitrypetukhov90.pythonanywhere.com/api/v1/costs/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

###
POST http://dmitrypetukhov90.pythonanywhere.com/api/v1/costs/1186342765
Content-type: application/json; charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU1NTgwNTUzLCJqdGkiOiIyZjE2YTZhZjg1OGQ0MDYwYjA1YjYwNWI2MTY1ODk0OCIsInVzZXJfaWQiOjN9.k7MyOPjIzQ43mZ-5r8OwB0v_Ri7nQasfEbaNGUAWdJc

{
    "cost": 185,
    "group": 2,
    "chat_id": 1186342765
}

###
GET http://127.0.0.1:8000/api/v1/costs/
Content-type: application/json; charset=utf-8
Authorization: Bearer f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

###
POST http://127.0.0.1:8000/api/v1/posts/2/comments/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "text": "Тестовый коммент6",
    "author": "username8"

}


###
POST http://127.0.0.1:8000/api/v1/groups/
Content-type: application/json; charset=utf-8
Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "title": "Разное",
    "slug": "Diff",
    "description": "Расходы без категорий."
}

###
GET http://127.0.0.1:8000/api/v1/costs/1186342765
Content-type: application/json; charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU1NjM2ODM0LCJqdGkiOiI1MzNhMWY1MzQxYjM0YWUxYWIyMmU5MmM4NWQzMDI0NyIsInVzZXJfaWQiOjF9.QVFDpwyZGirhbSMPve1WrTDtuhZq8LkGCMKc-FYO09M

{
    "cost": 185,
    "group": 1
}

###
POST http://127.0.0.1:8000/api/v1/costs/
Content-type: application/json; charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU1NjM2ODM0LCJqdGkiOiI1MzNhMWY1MzQxYjM0YWUxYWIyMmU5MmM4NWQzMDI0NyIsInVzZXJfaWQiOjF9.QVFDpwyZGirhbSMPve1WrTDtuhZq8LkGCMKc-FYO09M

{
    "cost": 185,
    "group": 2,
    "chat_id": 1186342765
}

###
POST http://127.0.0.1:8000/auth/jwt/create/
Content-type: application/json; charset=utf-8
#Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "username": "Dimon",
    "password": "20756320privet"
}

###
GET  http://127.0.0.1:8000/auth/users/
Content-type: application/json; charset=utf-8
#Authorization: Token f9fccb835d5d7d93a9b9aa35be0725ff4c0fcf01

{
    "username": "Dimon",
    "password": "20756320privet"
}

###
POST http://dmitrypetukhov90.pythonanywhere.com/auth/users/
Content-type: application/json; charset=utf-8
#Authorization: Token b7bb38ae368205d2a058554f96d28f8193634013

{
    "username": "Dimons",
    "password": "Privet4545*"
}

###
POST http://dmitrypetukhov90.pythonanywhere.com/auth/jwt/create/
Content-type: application/json; charset=utf-8
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU1NjY0NDMyLCJqdGkiOiJlYjY3ZmZmYTdiMGU0YmEzOTMyZDQ2ZjU4MTljOWMyMSIsInVzZXJfaWQiOjN9.ePbYAuYlCK3Q_2z7wG8o-fT1Cs0a40qoAHglrPGMjco

{
    "username": "Dimons",
    "password": "Privet4545*"
}